//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassFile
    {
        public int FileID { get; set; }
        public string File { get; set; }
        public Nullable<int> Activity_ActID { get; set; }
    
        public virtual Activity Activity { get; set; }
    }
}
