//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeID { get; set; }
        public int Value { get; set; }
        public int PersonPersonId { get; set; }
        public int ActivityActID { get; set; }
    
        public virtual Activity Activity { get; set; }
        public virtual Person Person { get; set; }
    }
}
