//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lab
    {
        public Lab()
        {
            this.LabID = 1;
            this.People = new HashSet<Person>();
        }
    
        public int LabID { get; set; }
        public string StudName { get; set; }
        public string InstrName { get; set; }
        public int ScheduleShedID { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
