//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        public int StuGrID { get; set; }
        public string GroupName { get; set; }
        public int ScheduleShedID { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
