//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public Activity()
        {
            this.Grades = new HashSet<Grade>();
            this.ClassFiles = new HashSet<ClassFile>();
        }
    
        public int ActID { get; set; }
        public string Name { get; set; }
        public string Property1 { get; set; }
        public int ScheduleShedID { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual ICollection<ClassFile> ClassFiles { get; set; }
        public virtual Schedule Schedule { get; set; }
    }
}
