//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassProject2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Grades = new HashSet<Grade>();
            this.Pictures = new HashSet<Picture>();
        }
    
        public int PersonId { get; set; }
        public string Fname { get; set; }
        public string Lname { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ClassID { get; set; }
        public int LabLabID { get; set; }
        public string PicturePictureID { get; set; }
    
        public virtual ICollection<Grade> Grades { get; set; }
        public virtual Lab Lab { get; set; }
        public virtual ICollection<Picture> Pictures { get; set; }
    }
}
